lib/boat.js, lib/bullet.js, lib/fish.js, lib/game.js
Contains boat and fishies to canvas
=> 11 boat visible

lib/collision.js, lib/game.js
Abstracts collision logic from game,
=> Abstracts collision logic into collision.js

lib/boat.js, lib/collision.js, lib/game.js, test/boat-test.js, test/bullet-test.js
- fish disappear upon bullet collision
=> 31 game collisions

lib/bullet.js, lib/game.js
Can fire one bullet at a time that persists the entire height of the canvas, regardless of a collision
=> 37 restrict bullets

index.html, lib/score.js
=> 20 styling

index.html, lib/boat.js, lib/bullet.js, lib/collision.js, lib/fish.js, lib/game.js, package.json
=> 24 view score

index.html, lib/game.js, package.json
=> Implements timer, removes jquery

index.html, lib/game.js
=> 19 player starts game

index.html, lib/fish.js, lib/game.js
=> 18 next round logic

lib/canvas-painter.js, lib/game.js
closes #56 
@jecrockett - refactor partner
@rrgayhart  - instructor
@dastinnette - member of another refactor team, please review!
What's this PR do?
Abstracts draw object functionality into a canvasPainter object. This removes responsibilities from the generateFish function in the game class.
Where should the reviewer start?
The canvasPainter object is exported Game object, then called in the drawObjects function rather than the generateFish function. This is more appropriate for single responsibility principles.  
How should this be manually tested?
This method draws to the canvas, which is hard to test. However, extracting this functionality will improve our ability to test generateFish and other fish properties that are not canvas related. 
Any background context you want to provide? …
=> 56 canvas painter

lib/bullet.js, lib/canvas-painter.js, lib/fish.js, lib/game.js
=> 58 abstract draw bullet

lib/boat.js, lib/canvas-painter.js, lib/game.js
=> 60 abstract draw boat

lib/boat.js, lib/bullet.js, lib/canvas-motion.js, lib/canvas-painter.js, lib/fish.js, lib/game.js
=> 62 canvas motion object

lib/boat.js, lib/bullet.js, lib/canvas-motion.js, lib/fish.js, lib/game.js, lib/stylesheets/canvas.css, test/boat-test.js, test/bullet-test.js, test/fish-test.js
=> 65 fix test suite

lib/bullet-shoot.js, lib/game.js
=> 74 clear score

index.html, lib/game.js, lib/stylesheets/canvas.css
=> 54 start new game

lib/game.js
=> Bullets clear when timer runs out

index.html, lib/game.js, lib/stylesheets/canvas.css
=> 50 scoring

index.html, lib/game.js, lib/stylesheets/canvas.css
=> 78 game instructions

index.html, lib/canvas-motion.js, lib/fish.js, lib/game.js, lib/stylesheets/canvas.css, sketch.js
closes #71 
@dastinnette @rrgayhart 
I got p5 working with fish motion dependent on the amplitude!!!
Lots to cover here...
- uses p5 to pull amplitude from song, create (artificial) DOM element on index.html
- call method within startGame loop to continously rip value from the DOM (using jQuery) and store the result inside a p5Amplitude variable
- passed p5Amplitude with the game loop to the moveFish function as an argument
- move fish then passes p5Amplitude to each methods (moveFishX and moveFishY)
Notes:
- Also created a fishMoveY function that takes the amplitude and allows shrink to very slowly descend off the bottom of the screen. I like this because it rewards a quick trigger for bottom feeders. 
- Breaks tests, primarily because p5Amplitude is not defined
- resets fish speeds well …
=> 71 p5 velocity

lib/fish.js, test/collision-test.js
=> 99 additional collision testing
